### ISSUE TITLE
Modify CSS for the Profile page

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#14]
<img width="1437" alt="Screenshot 1943-11-12 at 00 09 18" src="https://user-images.githubusercontent.com/78296094/151853002-d64e0151-dba5-4fc2-a4f6-973060d369a0.png">

**Comment by Debdeep1** [comment]
I want to work on this issue under JWOC.

**Comment by soumali28** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

Yes you can 👍

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

Sorry but @soumali28 asked for this issue earlier….you can create new issues and can contribute in those👍

**Comment by Tess-Vanta** [comment]
I want to work on this issue under JWOC .

**Comment by ronitblenz** [comment]
Hey, I have 3 PRs  got merged and participated in 6-7 hackathons,
I am willing to take up this issue under JWOC

Thanks and Regards

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

Hey @whiteHatpro ...if you are not working with any issue....do you want to take up with this issue? Else I'll assign it to @Tess-Vanta .

**Comment by riyajha2305** [comment]
> Hey, I have 3 PRs got merged and participated in 6-7 hackathons, I am willing to take up this issue under JWOC
> 
> Thanks and Regards

Hello @ronitblenz ... I apologise for this but I need to first confirm from @Tess-Vanta and @whiteHatpro if they want to take up with this issue....cuz issue assignment is based purely on First come first serve basis. Meanwhile you can look for other issues as well..there are more easy issues on this repo.

**Comment by ronitblenz** [comment]
Sure, ask them first. Community works on these norms ...I am not an exception 😊❤️

**Comment by Tess-Vanta** [comment]
> > Hey, I have 3 PRs got merged and participated in 6-7 hackathons, I am willing to take up this issue under JWOC
> > 
> > Thanks and Regards
> 
> Hello @ronitblenz ... I apologise for this but I need to first confirm from @Tess-Vanta and @whiteHatpro if they want to take up with this issue....cuz issue assignment is based purely on First come first serve basis. Meanwhile you can look for other issues as well..there are more easy issues on this repo.

I would like to take it up ☺️

**Comment by riyajha2305** [comment]
> > > Hey, I have 3 PRs got merged and participated in 6-7 hackathons, I am willing to take up this issue under JWOC
> > > Thanks and Regards
> > 
> > 
> > Hello @ronitblenz ... I apologise for this but I need to first confirm from @Tess-Vanta and @whiteHatpro if they want to take up with this issue....cuz issue assignment is based purely on First come first serve basis. Meanwhile you can look for other issues as well..there are more easy issues on this repo.
> 
> I would like to take it up ☺️

Yeah @Tess-Vanta .... you can go for it👍

**Comment by riyajha2305** [comment]
> Sure, ask them first. Community works on these norms ...I am not an exception 😊❤️

Hey @ronitblenz .... I have an easy yet quick issue #28 .... if you wanna contribute you can go ahead 👍

**Comment by ronitblenz** [comment]
> > Sure, ask them first. Community works on these norms ...I am not an exception 😊❤️
> 
> Hey @ronitblenz .... I have an easy yet quick issue #28 .... if you wanna contribute you can go ahead 👍

Sure ...😊

**Comment by ronitblenz** [comment]
Give me the issue

**Comment by riyajha2305** [comment]
> Give me the issue

Actually u need to comment under that issue asking if you can work under JWOC … as per the rules.

**Comment by ronitblenz** [comment]
Ok sure, can you mention the issue number, so that I can figure out which one you are talking about

**Comment by ronitblenz** [comment]
I have made a request, kindly check
