### ISSUE TITLE
Incorporate Google signin/signup authentication to the signin/signup page

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#15]

**Comment by AnandSY** [comment]
Hi riya !! I want to work on this issue ,please assign it to me, thanks.

**Comment by riyajha2305** [comment]
> Hi riya !! I want to work on this issue ,please assign it to me, thanks.

Hello...sure...go for it👍

**Comment by AnandSY** [comment]
sorry, i forgot to write "under JWOC". I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> sorry, i forgot to write "under JWOC". I want to work on this issue under JWOC.

yeah .. alright

**Comment by harshit-070** [comment]
I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC.

yep....go ahead👍🔥

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC.
