### ISSUE TITLE
Modify CSS for create post page

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#17]

**Comment by swetanklabs** [comment]
I would like to work under this issue.Please assign it to me.

**Comment by riyajha2305** [comment]
> I would like to work under this issue.Please assign it to me.

yes sure 👍

**Comment by raxvab** [comment]
I want to work on this issue under JWOC

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

Hey @raxvab … glad to see your interest towards contributing in this issue but this has already been aasigned to @stubborn-1508 …. You could see other issues on this repo or could even create your own if you find any.

**Comment by swetanklabs** [comment]
![Screenshot (213)](https://user-images.githubusercontent.com/87987269/152059041-ce1a2e78-43d1-46bc-a331-b20615ab1484.png)
@riyajha2305 I have done the desired changes in the CSS layout.Please review it.
