### ISSUE TITLE
Apply the font-style as in the real Instagram throughout the website

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#18]

**Comment by aditi-gosain** [comment]
I would like to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I would like to work on this issue under JWOC.

yeah sure👍😁

**Comment by ChandreshBabu** [comment]
I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC.

yes you can 👍

**Comment by Shruti025** [comment]
hey can I work on this issue under JWOC?

**Comment by riyajha2305** [comment]
> hey can I work on this issue under JWOC?

Yes you can ✌️
