### ISSUE TITLE
All commenters' names disappear from the comment section after the user likes/dislikes the post.

### ISSUE THREAD

**Issue by dhruvtongia** [riyajha2305/Instagram-Clone#23]
All commenters' names disappear from the comment section after the user likes/dislikes the post. One has to refresh the page to see the commenters' names again.

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC.

yes go for it
