### ISSUE TITLE
Incorporate signin/signup through facebook feature on the signin/signup page

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#27]

**Comment by harshit-070** [comment]
I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC.

yes all the best👍

**Comment by 03amir** [comment]
I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC.

Sorry but it has. been solved by @harshit-070
