### ISSUE TITLE
Make equal spacing between nav-items icons on the navbar

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#28]

**Comment by ronitblenz** [comment]
Hi, I am willing to work on this issue
(jwoc)

**Comment by riyajha2305** [comment]
> Hi, I am willing to work on this issue
> (jwoc)

Yeah go for it ✌️ All the best

**Comment by ronitblenz** [comment]
I am sorry @riyajha2305 I was unable to solve the issue due to inexperience in React, You can Unassign me from the issue.
I apologise for that.

Thanks for mentoring me and giving me time more than I should have got.

**Comment by riyajha2305** [comment]
> I am sorry @riyajha2305 I was unable to solve the issue due to inexperience in React, You can Unassign me from the issue. I apologise for that.
> 
> Thanks for mentoring me and giving me time more than I should have got.

Yep....no issue. Good luck!

**Comment by Devmindtk** [comment]
I would like to work on this issue.please assign it to me

**Comment by riyajha2305** [comment]
> I would like to work on this issue.please assign it to me

Yes go ahead 👍

**Comment by Devmindtk** [comment]
@riyajha2305 should I have to make equal spacing between all the nav-items icon on right side nav menu right?

**Comment by Devmindtk** [comment]
![Screenshot (465)](https://user-images.githubusercontent.com/91221069/152933960-8fd859d6-851d-4bbe-b969-02a440053432.png)

between this item?

**Comment by Devmindtk** [comment]
![Screenshot (467)](https://user-images.githubusercontent.com/91221069/152935765-d2ae9de4-5ebb-447e-9d29-667ba7e14311.png)

@riyajha2305  check this is it fine now or anything else you want to change like all the nav items in center with equal spacing or what?

**Comment by ronitblenz** [comment]
Hey, @Devmindtk How did you do that, actually I was assigned with the issue a few days back, but I dont have proper knowledge about react,Thats why I asked the mentor to unassign me, could you plz tell me what did you change in the code to make it happen, it would be great help

**Comment by Devmindtk** [comment]
> Hey, @Devmindtk How did you do that, actually I was assigned with the issue a few days back, but I dont have proper knowledge about react,Thats why I asked the mentor to unassign me, could you plz tell me what did you change in the code to make it happen, it would be great help

Hey @ronitblenz  I don't know actually is it right or not whatever i have done. Just added paading left and right in css nothing else.

**Comment by ronitblenz** [comment]
> > Hey, @Devmindtk How did you do that, actually I was assigned with the issue a few days back, but I dont have proper knowledge about react,Thats why I asked the mentor to unassign me, could you plz tell me what did you change in the code to make it happen, it would be great help
> 
> Hey @ronitblenz  I don't know actually is it right or not whatever i have done. Just added paading left and right in css nothing else.

Could you plz inbox me in discord, actually I couldnt find the part to edit in css... My disc id is @ronitblenz#6939

I just need to figure out what was needed to change

**Comment by Devmindtk** [comment]
> > > Hey, @Devmindtk How did you do that, actually I was assigned with the issue a few days back, but I dont have proper knowledge about react,Thats why I asked the mentor to unassign me, could you plz tell me what did you change in the code to make it happen, it would be great help
> > 
> > 
> > Hey @ronitblenz  I don't know actually is it right or not whatever i have done. Just added paading left and right in css nothing else.
> 
> Could you plz inbox me in discord, actually I couldnt find the part to edit in css... My disc id is @ronitblenz#6939
> 
> I just need to figure out what was needed to change

sure.

**Comment by riyajha2305** [comment]
> ![Screenshot (467)](https://user-images.githubusercontent.com/91221069/152935765-d2ae9de4-5ebb-447e-9d29-667ba7e14311.png)
> 
> @riyajha2305 check this is it fine now or anything else you want to change like all the nav items in center with equal spacing or what?

Umm....u need to clone  the latest updated repo from the master branch.....nav items have been replaced by icons.
<img width="1438" alt="Screenshot 1943-11-19 at 15 34 31" src="https://user-images.githubusercontent.com/78296094/152964907-6d3616f1-5942-460f-8648-1a9b1d0a0a94.png">
Now u can make the changes.

**Comment by Devmindtk** [comment]
> > ![Screenshot (467)](https://user-images.githubusercontent.com/91221069/152935765-d2ae9de4-5ebb-447e-9d29-667ba7e14311.png)
> > @riyajha2305 check this is it fine now or anything else you want to change like all the nav items in center with equal spacing or what?
> 
> Umm....u need to clone the latest updated repo from the master branch.....nav items have been replaced by icons. <img alt="Screenshot 1943-11-19 at 15 34 31" width="1438" src="https://user-images.githubusercontent.com/78296094/152964907-6d3616f1-5942-460f-8648-1a9b1d0a0a94.png"> Now u can make the changes.

i think the repository link u have uploaded is not updated

**Comment by Devmindtk** [comment]
i am trying to signup but it is not working @riyajha2305

**Comment by riyajha2305** [comment]
> > > ![Screenshot (467)](https://user-images.githubusercontent.com/91221069/152935765-d2ae9de4-5ebb-447e-9d29-667ba7e14311.png)
> > > @riyajha2305 check this is it fine now or anything else you want to change like all the nav items in center with equal spacing or what?
> > 
> > 
> > Umm....u need to clone the latest updated repo from the master branch.....nav items have been replaced by icons. <img alt="Screenshot 1943-11-19 at 15 34 31" width="1438" src="https://user-images.githubusercontent.com/78296094/152964907-6d3616f1-5942-460f-8648-1a9b1d0a0a94.png"> Now u can make the changes.
> 
> i think the repository link u have uploaded is not updated

Yes, I haven’t yet pushed changes to the deloyed link bht the repo is updated …. Go through the latest version of repo.

**Comment by riyajha2305** [comment]
> i am trying to signup but it is not working @riyajha2305

I checked it …. It’s working fine for me. After signjng up you should sign in using that email and password. Did u do that?

**Comment by Devmindtk** [comment]
> i am trying to signup but it is not working @riyajha2305

i am facing this issue how to go to home page to see nav bar

**Comment by Devmindtk** [comment]
> > i am trying to signup but it is not working @riyajha2305
> 
> I checked it …. It’s working fine for me. After signjng up you should sign in using that email and password. Did u do that?

yes after signup page is not going to next page and its is just as static

**Comment by riyajha2305** [comment]
step 1. click on sign up button below
<img width="1436" alt="1" src="https://user-images.githubusercontent.com/78296094/152974385-67508ab4-2a68-4725-965c-ad6bd7a34142.png">

step 2. fill your details and click sign up
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/78296094/152974398-20cacd86-ae08-4052-b6e9-20edbce155f6.png">

step 3. fill you details again and click sign in 
<img width="1437" alt="3" src="https://user-images.githubusercontent.com/78296094/152974407-e407ddcf-b24d-4495-aeac-7915b2bef20a.png">

step 4. you'll be directed to the main page
<img width="1436" alt="4" src="https://user-images.githubusercontent.com/78296094/152974429-cb40d708-6efe-48d6-a0c7-04d634c8f2bf.png">

**Comment by Devmindtk** [comment]
there is showing error some proxy request  
Proxy error: Could not proxy request /allpost from localhost:3000 to http://localhost:5000/.
 
check this screenrecording


https://user-images.githubusercontent.com/91221069/152976122-e9181e08-f1da-445f-b519-a0a9752cf1a2.mp4

**Comment by riyajha2305** [comment]
> there is showing error some proxy request check this screenrecording
> 
>  WhatsApp.Video.2022-02-08.at.16.35.09.mp4

Did u run both the servers backend as well as frontend?

**Comment by Devmindtk** [comment]
> > there is showing error some proxy request check this screenrecording
> > WhatsApp.Video.2022-02-08.at.16.35.09.mp4
> 
> Did u run both the servers backend as well as frontend?

no only react as written in readme file

**Comment by riyajha2305** [comment]
> > > there is showing error some proxy request check this screenrecording
> > > WhatsApp.Video.2022-02-08.at.16.35.09.mp4
> > 
> > 
> > Did u run both the servers backend as well as frontend?
> 
> no only react as written in readme file

That is the reason....I have stated clearly in readme.md both the servers are needed to be run in order to run this project on your local system.

**Comment by riyajha2305** [comment]
> > > > there is showing error some proxy request check this screenrecording
> > > > WhatsApp.Video.2022-02-08.at.16.35.09.mp4
> > > 
> > > 
> > > Did u run both the servers backend as well as frontend?
> > 
> > 
> > no only react as written in readme file
> 
> That is the reason....I have stated clearly in readme.md both the servers are needed to be run in order to run this project on your local system.

U may refer to this screen recording to run the project on your local.
https://drive.google.com/file/d/122vN65SZkysGoAIPlnu9-zZzqigl0f4_/view?usp=sharing

**Comment by Devmindtk** [comment]
> > > > > there is showing error some proxy request check this screenrecording
> > > > > WhatsApp.Video.2022-02-08.at.16.35.09.mp4
> > > > 
> > > > 
> > > > Did u run both the servers backend as well as frontend?
> > > 
> > > 
> > > no only react as written in readme file
> > 
> > 
> > That is the reason....I have stated clearly in readme.md both the servers are needed to be run in order to run this project on your local system.
> 
> U may refer to this screen recording to run the project on your local. https://drive.google.com/file/d/122vN65SZkysGoAIPlnu9-zZzqigl0f4_/view?usp=sharing

okay thanks a lot

**Comment by Devmindtk** [comment]
Now its working fine.Thank you @riyajha2305

**Comment by riyajha2305** [comment]
> Now its working fine.Thank you @riyajha2305

great. All the best👍

**Comment by Devmindtk** [comment]
> > Now its working fine.Thank you @riyajha2305
> 
> great. All the best👍
![Screenshot (474)](https://user-images.githubusercontent.com/91221069/152981035-25d09830-17e7-4920-ab4d-a46589ba6a4f.png)

check this @riyajha2305 
more space is required?

**Comment by Devmindtk** [comment]
![Screenshot (475)](https://user-images.githubusercontent.com/91221069/152981930-c77e42f4-3981-45ed-be81-c0a124cc2960.png)

**Comment by riyajha2305** [comment]
> > > Now its working fine.Thank you @riyajha2305
> > 
> > 
> > great. All the best👍
> > ![Screenshot (474)](https://user-images.githubusercontent.com/91221069/152981035-25d09830-17e7-4920-ab4d-a46589ba6a4f.png)
> 
> check this @riyajha2305 more space is required?

That looks great @Devmindtk ... can you even align that logout button along with those nav items?

**Comment by Devmindtk** [comment]
> > > > Now its working fine.Thank you @riyajha2305
> > > 
> > > 
> > > great. All the best👍
> > > ![Screenshot (474)](https://user-images.githubusercontent.com/91221069/152981035-25d09830-17e7-4920-ab4d-a46589ba6a4f.png)
> > 
> > 
> > check this @riyajha2305 more space is required?
> 
> That looks great @Devmindtk ... can you even align that logout button along with those nav items?

Yeah sure @riyajha2305

**Comment by Devmindtk** [comment]
> > > > > Now its working fine.Thank you @riyajha2305
> > > > 
> > > > 
> > > > great. All the best👍
> > > > ![Screenshot (474)](https://user-images.githubusercontent.com/91221069/152981035-25d09830-17e7-4920-ab4d-a46589ba6a4f.png)
> > > 
> > > 
> > > check this @riyajha2305 more space is required?
> > 
> > 
> > That looks great @Devmindtk ... can you even align that logout button along with those nav items?
> 
> Yeah sure @riyajha2305

check now the alignment of button is fine now?
@riyajha2305 
![Screenshot (489)](https://user-images.githubusercontent.com/91221069/153356816-d3db3f9a-e382-490e-9f0d-a863717e24cb.png)

**Comment by riyajha2305** [comment]
> > > > > > Now its working fine.Thank you @riyajha2305
> > > > > 
> > > > > 
> > > > > great. All the best👍
> > > > > ![Screenshot (474)](https://user-images.githubusercontent.com/91221069/152981035-25d09830-17e7-4920-ab4d-a46589ba6a4f.png)
> > > > 
> > > > 
> > > > check this @riyajha2305 more space is required?
> > > 
> > > 
> > > That looks great @Devmindtk ... can you even align that logout button along with those nav items?
> > 
> > 
> > Yeah sure @riyajha2305
> 
> check now the alignment of button is fine now? @riyajha2305 ![Screenshot (489)](https://user-images.githubusercontent.com/91221069/153356816-d3db3f9a-e382-490e-9f0d-a863717e24cb.png)

Superb 🔥🔥🔥🔥. Give me some time I’ll just merge it.

**Comment by riyajha2305** [comment]
> > > > > > Now its working fine.Thank you @riyajha2305
> > > > > 
> > > > > 
> > > > > great. All the best👍
> > > > > ![Screenshot (474)](https://user-images.githubusercontent.com/91221069/152981035-25d09830-17e7-4920-ab4d-a46589ba6a4f.png)
> > > > 
> > > > 
> > > > check this @riyajha2305 more space is required?
> > > 
> > > 
> > > That looks great @Devmindtk ... can you even align that logout button along with those nav items?
> > 
> > 
> > Yeah sure @riyajha2305
> 
> check now the alignment of button is fine now? @riyajha2305 ![Screenshot (489)](https://user-images.githubusercontent.com/91221069/153356816-d3db3f9a-e382-490e-9f0d-a863717e24cb.png)

did u make a pr?
