### ISSUE TITLE
Modify the CSS of the other user's profile page similar to that of current user's profile page.

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#31]
current user's profile page

<img width="807" alt="profile page" src="https://user-images.githubusercontent.com/78296094/152559335-298a6101-1d49-40a3-9b26-29aedf505b82.png">

other user's profile page

<img width="1431" alt="userprofile page" src="https://user-images.githubusercontent.com/78296094/152559400-02c78509-5ab2-4fd0-9e40-cef8802c6f10.png">

**Comment by Tess-Vanta** [comment]
can i take up this one under JWOC?

**Comment by riyajha2305** [comment]
> can i take up this one under JWOC?

Sure…haha😂✌️
