### ISSUE TITLE
Separate css files

### ISSUE THREAD

**Issue by Shruti025** [riyajha2305/Instagram-Clone#34]
Create separate css files for the js files of various pages.

**Comment by riyajha2305** [comment]
> Create separate css files for the js files of various pages.

If you want to work you can ask in the comment below

**Comment by Shruti025** [comment]
oh okay, can I work on this issue under JWOC? @riyajha2305

**Comment by riyajha2305** [comment]
> oh okay, can I work on this issue under JWOC? @riyajha2305

yes go for it👍
