### ISSUE TITLE
Likes counts are incorrect

### ISSUE THREAD

**Issue by Starboy-Sharma** [riyajha2305/Instagram-Clone#42]
If you click the like button multiple time so the like count increase more than once. Same with comment if you are posting any comment and press enter multiple times then your comment visible more than once.

**Comment by Amit91848** [comment]
Can I work on this?

**Comment by riyajha2305** [comment]
> If you click the like button multiple time so the like count increase more than once. Same with comment if you are posting any comment and press enter multiple times then your comment visible more than once.

Did you clone the repo and check the issue? Or are you saying this by seeing the deployed link?
Also the website isn't responsive till this stage. So, if viewing on mobile then this bug might occur. Do you want to work on this issue for responsive view?

**Comment by riyajha2305** [comment]
> > If you click the like button multiple time so the like count increase more than once. Same with comment if you are posting any comment and press enter multiple times then your comment visible more than once.
> 
> Did you clone the repo and check the issue? Or are you saying this by seeing the deployed link? Also the website isn't responsive till this stage. So, if viewing on mobile then this bug might occur. Do you want to work on this issue for responsive view?

Any updates?

**Comment by Starboy-Sharma** [comment]
Sorry I was quite busy. Yes I would like to fix the bug. Thanks
