### ISSUE TITLE
Align the bin icon on the right-most side of the post header

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#44]
<img width="1275" alt="Screenshot 1943-11-23 at 12 37 28" src="https://user-images.githubusercontent.com/78296094/153701126-9cf8cc36-8aa2-440c-a678-759298bc97d4.png">

**Comment by Tess-Vanta** [comment]
I would like to take this up under JWOC

**Comment by riyajha2305** [comment]
> I would like to take this up under JWOC

ok
