### ISSUE TITLE
The profile icon disappears on clicking like button on any post.

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#45]
<img width="1215" alt="Screenshot 1943-11-23 at 12 36 21" src="https://user-images.githubusercontent.com/78296094/153701200-4367b0d9-0a94-4c02-881b-e88908763bc1.png">

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC

**Comment by dhruvtongia** [comment]
I want to work on this issue under JWOC

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC
Ok sir
