### ISSUE TITLE
Create a logo for the website using any designing tool For eg: figma, adobe photoshop etc.

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#46]

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-508** [comment]
@riyajha2305 I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

ok go for it

**Comment by Aniket-508** [comment]
@riyajha2305 Can you please assign me this as well?

**Comment by binayshaw7777** [comment]
> > I want to work on this issue under JWOC
> 
> ok go for it

You've not assigned me yet.

**Comment by riyajha2305** [comment]
> @riyajha2305 Can you please assign me this as well? Should be exactly like instagram or similar to it?

sorry but @binayshaw7777 asked earlier.
