### ISSUE TITLE
Modify CSS for the signin / signup page as that of the actual Instagram.

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#5]
This is a beginner-friendly issue based on CSS. I want the signin / signup page to look similar to the one of the actual instagram page. I am attaching the screenshot of what I actually want the page to look like for reference.
<img width="1426" alt="Screenshot 1943-11-09 at 14 19 01" src="https://user-images.githubusercontent.com/78296094/151654639-a05c01d8-31d8-46c3-888f-1f702ce1ad24.png">

**Comment by Ankushpanday1** [comment]
Can i work on this issue?

**Comment by riyajha2305** [comment]
> Can i work on this issue?

Yeah sure...but as per the guidelines of JWOC, contributions will only be valid from Feb 1st onwards. But if you wanna just contribute to this issue irrespective of the JWOC points...u surely can? Do lemme know your decision.

**Comment by Shresa** [comment]
I want to work on this issue under JWOC

**Comment by lavakush07** [comment]
"I want to work on this issue under JWOC"

**Comment by Arun5023** [comment]
"I want to work on this issue under JWOC"

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

yeah you can ....👍

**Comment by riyajha2305** [comment]
> "I want to work on this issue under JWOC"

I'm sorry .... as this was FCFS ....you can try out on other issues on the repo or can create your own issue and contribute

**Comment by riyajha2305** [comment]
> "I want to work on this issue under JWOC"

I'm sorry .... as this was FCFS ....you can try out on other issues on the repo or can create your own issue and contribute

**Comment by raxvab** [comment]
Can you elaborate how we can create our own issue and contribute ??

**Comment by riyajha2305** [comment]
> Can you elaborate how we can create our own issue and contribute ??

Yeah sure….you can visit the deployed link 👉 https://instaclone2305.herokuapp.com/ of this project and can observe things there. ( Hint : as this is a clone of Instagram you can compare these two websites and find any missing feature at your level. ) 


And once you got an issue of yours you can go to issues->new issue-> write the title and description of your issue -> submit new issue


I’ll then observe your issue and assign it to you accordingly.✌️

**Comment by riyajha2305** [comment]
> > I want to work on this issue under JWOC
> 
> yeah you can ....👍

@Shresa .... it's more than a day now.....I want an update on this issue you are working on....else I'll pass this issue to @lavakush07 . I'll wait for the reply until 8am tomorrow.
