### ISSUE TITLE
Documentation : Readme Updatation 

### ISSUE THREAD

**Issue by ayush-sleeping** [riyajha2305/Instagram-Clone#55]
Add - labels ,
Add - Table of content ,
Add - Open Source programs this repo has been part of ,
Add - Project Mentor ,
Add - ( back to top ) and ( bottom ) links ,
Add - Contributors section ,
Add - Feedback section ,
Also - All things categorize it, In a systematic way ......

<br>

#

Hey @riyajha2305 , I want to work on this issue under JWOC'22 
And want to make the Readme file of this Repo. more responsive and cool .

**Comment by riyajha2305** [comment]
> Add - labels , Add - Table of content , Add - Open Source programs this repo has been part of , Add - Project Mentor , Add - ( back to top ) and ( bottom ) links , Add - Contributors section , Add - Feedback section , Also - All things categorize it, In a systematic way ......
> 
> 
> Hey @riyajha2305 , I want to work on this issue under JWOC'22 And want to make the Readme file of this Repo. more responsive and cool .

Great ! Though I have a separate README already under .github/ you can modify the main README as well.
