### ISSUE TITLE
Add this image to the website's logo

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#59]
.png format - https://github.com/riyajha2305/Instagram-Clone/blob/master/screenshots/Logo.png

![Logo](https://user-images.githubusercontent.com/78296094/153997797-d2e41e35-9d03-4b2f-8fec-012446ab87d3.png)

.svg format - https://github.com/riyajha2305/Instagram-Clone/blob/master/screenshots/Logo.svg

![Logo](https://user-images.githubusercontent.com/78296094/153997822-4b5e1999-865e-4071-891b-88a8b4ec5307.svg)
/screenshots/Logo.svg

**Comment by Anirban-1490** [comment]
adding the .png to the logo in the navbar only ? @riyajha2305

**Comment by riyajha2305** [comment]
> adding the .png to the logo in the navbar only ? @riyajha2305

No even as the icon of the website….that we see on tabs

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by Nimishavashistha** [comment]
I want to work on this issue under jwoc

**Comment by Nimishavashistha** [comment]
I want to work on this issue under jwoc

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

Yes u can
