### ISSUE TITLE
Modify the UI of navbar similar to actual Instagram (PS: do not change the nav-items icons)

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#62]
<img width="1440" alt="Screenshot 1943-11-28 at 19 28 49" src="https://user-images.githubusercontent.com/78296094/154497696-2c7b037a-05af-4043-808f-07d05300caaa.png">

make it similar to this
<img width="1431" alt="Screenshot 1943-11-28 at 19 38 05" src="https://user-images.githubusercontent.com/78296094/154498560-bb79d574-d177-46ae-958a-4940cf302669.png">

**Comment by Tess-Vanta** [comment]
i want to take this up under JWOC

**Comment by riyajha2305** [comment]
> i want to take this up under JWOC

Yeah sure
