### ISSUE TITLE
Add update profile page with fields like update username, bio, description.

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#63]

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by riyajha2305** [comment]
> I want to work on this under JWOC

Yes you can! Sorry for the delay in response…the repo faced certain bugs and I waa busy fixing it. You can now work on this issue.

**Comment by Shruti025** [comment]
> Yes you can! Sorry for the delay in response…the repo faced certain bugs and I waa busy fixing it. You can now work on this issue.

Thank you, also I guess to forgot to assign me the issue. Could you do that please?

**Comment by riyajha2305** [comment]
> > Yes you can! Sorry for the delay in response…the repo faced certain bugs and I waa busy fixing it. You can now work on this issue.
> 
> Thank you, also I guess to forgot to assign me the issue. Could you do that please?

Yeah…done!
