### ISSUE TITLE
Add Home icon on the navbar and link it to home page

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#64]

**Comment by Nimishavashistha** [comment]
I want to work on this issue under JWOC

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC


> I want to work on this issue under JWOC

Hey @Nimishavashistha ….. I’ll assign you this issue but could you please start working after an issue on redesign of the navbar has been solved. After the resdesigning of the navbar has been done you can then add the home icon. I hope you understand

**Comment by Nimishavashistha** [comment]
Okay

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC

This issue has been solved. I’m sorry for the inconvenience.
