### ISSUE TITLE
replace the profile icon with user's profile picture on nav-bar 

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#65]

**Comment by Tess-Vanta** [comment]
I want to take this up under JWOC

**Comment by riyajha2305** [comment]
> I want to take this up under JWOC

Yeah sure

**Comment by Tess-Vanta** [comment]
Hey, sorry im not able to complete this. I'll unassign myself ;(

**Comment by 03amir** [comment]
I want to take this up under JWOC

**Comment by riyajha2305** [comment]
> Hey, sorry im not able to complete this. I'll unassign myself ;(

no worries

**Comment by riyajha2305** [comment]
> I want to take this up under JWOC

yeah sure
