### ISSUE TITLE
Incorporate password regex in the signin / signup page for password verification

### ISSUE THREAD

**Issue by riyajha2305** [riyajha2305/Instagram-Clone#7]

**Comment by valanm22** [comment]
I want to work on this issue under JWOC.

**Comment by riyajha2305** [comment]
> I want to work on this issue under JWOC.

Yeah sure @valanm22 ... go for it👍

**Comment by riyajha2305** [comment]
> > I want to work on this issue under JWOC.
> 
> Yeah sure @valanm22 ... go for it👍

@valanm22 ... can I get an update on your work ? Do you need more time?

**Comment by valanm22** [comment]
Sorry @riyajha2305. Couldn't figure it out. Please reassign this issue.

**Comment by riyajha2305** [comment]
> Sorry @riyajha2305. Couldn't figure it out. Please reassign this issue.

Do you wanna drop out??

**Comment by valanm22** [comment]
Yes

**Comment by riyajha2305** [comment]
> Yes

Ok no worries

**Comment by Devmindtk** [comment]
I would like to work on this issue .please assign it to me

**Comment by riyajha2305** [comment]
> I would like to work on this issue .please assign it to me

Yes u can

**Comment by Devmindtk** [comment]
@riyajha2305  do you want to add confirm passowrd input box more alongwith regex validation?

**Comment by riyajha2305** [comment]
> @riyajha2305 do you want to add confirm passowrd input box more alongwith regex validation?

Yes

**Comment by Devmindtk** [comment]
@riyajha2305  i have created this one till now.please let me know what do you want to show as error istead of invalid word.
![Screenshot (491)](https://user-images.githubusercontent.com/91221069/153407873-0109f1d0-e1cc-46c6-ae06-fd8662f84c1a.png)

**Comment by riyajha2305** [comment]
> @riyajha2305 i have created this one till now.please let me know what do you want to show as error istead of invalid word.
> ![Screenshot (491)](https://user-images.githubusercontent.com/91221069/153407873-0109f1d0-e1cc-46c6-ae06-fd8662f84c1a.png)

Yeah the code looks good. Give me time by today night, I’ll merge it.

**Comment by Devmindtk** [comment]
> > @riyajha2305 i have created this one till now.please let me know what do you want to show as error istead of invalid word.
> > ![Screenshot (491)](https://user-images.githubusercontent.com/91221069/153407873-0109f1d0-e1cc-46c6-ae06-fd8662f84c1a.png)
> 
> Yeah the code looks good. Give me time by today night, I’ll merge it.

I have not created PR yet facing issue in creating PR.please help me out @riyajha2305

**Comment by riyajha2305** [comment]
> > @riyajha2305 i have created this one till now.please let me know what do you want to show as error istead of invalid word.
> > ![Screenshot (491)](https://user-images.githubusercontent.com/91221069/153407873-0109f1d0-e1cc-46c6-ae06-fd8662f84c1a.png)
> 
> Yeah the code looks good. Give me time by today night, I’ll merge it.

Have you made a pr?

**Comment by Devmindtk** [comment]
> > > @riyajha2305 i have created this one till now.please let me know what do you want to show as error istead of invalid word.
> > > ![Screenshot (491)](https://user-images.githubusercontent.com/91221069/153407873-0109f1d0-e1cc-46c6-ae06-fd8662f84c1a.png)
> > 
> > 
> > Yeah the code looks good. Give me time by today night, I’ll merge it.
> 
> Have you made a pr?

Not yet geeting an error in creating PR

**Comment by riyajha2305** [comment]
> > > > @riyajha2305 i have created this one till now.please let me know what do you want to show as error istead of invalid word.
> > > > ![Screenshot (491)](https://user-images.githubusercontent.com/91221069/153407873-0109f1d0-e1cc-46c6-ae06-fd8662f84c1a.png)
> > > 
> > > 
> > > Yeah the code looks good. Give me time by today night, I’ll merge it.
> > 
> > 
> > Have you made a pr?
> 
> Not yet geeting an error in creating PR

ok....you can tell me by tomorrow then.
