### ISSUE TITLE
Redesign Homepage

### ISSUE THREAD

**Issue by rockingrohit9639** [riyajha2305/Instagram-Clone#73]
Hey there, 
As far as I know, it is an Instagram clone but the app does not look like Instagram. I would like to redesign the Homepage using CSS to look more like Instagram. 
If you allow me @riyajha2305 I would be happy to do so.

**Comment by riyajha2305** [comment]
> Hey there,
> As far as I know, it is an Instagram clone but the app does not look like Instagram. I would like to redesign the Homepage using CSS to look more like Instagram.
> If you allow me @riyajha2305 I would be happy to do so.

Ok you can ✌️
