### ISSUE TITLE
Design the profile page similar to actual instagram

### ISSUE THREAD

**Issue by Tess-Vanta** [riyajha2305/Instagram-Clone#86]
I want to modify the profile page

<img width="861" alt="image" src="https://user-images.githubusercontent.com/72697074/156866515-9a38da58-80b6-4878-b274-c2403538bcf5.png">

**Comment by riyajha2305** [comment]
> I want to modify the profile page
> 
> <img alt="image" width="861" src="https://user-images.githubusercontent.com/72697074/156866515-9a38da58-80b6-4878-b274-c2403538bcf5.png">

Yep sure
